name: 'riverpod_graph action'
description: 'Run riverpod_graph'
author: 'noboru-i'
runs:
  using: 'composite'
  steps:
    - id: riverpod_graph-action
      run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: graph
        path: graph.md
